apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: buildkit
spec:
  selector:
    app: server
  ports:
  - name: main
    port: 80
    targetPort: main
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: buildkit
spec:
  selector:
    matchLabels:
      app: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: server
      annotations:
        container.apparmor.security.beta.kubernetes.io/server: unconfined
    spec:
      initContainers:
        - name: init
          image: busybox:latest
          command: ["sh","-c","mkdir -p /var/lib/buildkit && chown -R 1000:1000 /var/lib/buildkit && mkdir -p /home/user/.local/tmp && chown -R 1000:1000 /home/user/"]
          resources:
          volumeMounts:
            - mountPath: /home/user
              name: cache
            - mountPath: /var/lib/buildkit
              name: cache
      containers:
        - name: server
          image: moby/buildkit:v0.10.6-rootless@sha256:af44d4fe353f26a8b79bf09fd1897459a529ac2f2a7bea769c2da10e50d87176
          args:
            - --addr
            - unix:///run/user/1000/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:80
            - --oci-worker-no-process-sandbox
            - --oci-worker-gc-keepstorage
            - "25000"
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            # Needs Kubernetes >= 1.19
            seccompProfile:
              type: Unconfined
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - name: main
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /home/user
              name: cache
            - mountPath: /var/lib/buildkit
              name: cache
          resources:
            requests:
              memory: "500M"
              cpu: "0.5"
            limits:
              memory: "2.5G"
              cpu: "1.5"
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: cache
