apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: buildkit
  name: cache
spec:
  storageClassName: yc-network-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
