# echo -n 'secret' | base64
# How to view password: `kubectl get secret github-secret -n drone -o jsonpath='{.data.secret}' | base64 -d`.
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: drone
type: Opaque
data:
  secret: "<base64>"
