# How to generate password: `cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 64 | base64 -w0`.
# How to view password: `kubectl get secret runner-secret -n drone -o jsonpath='{.data.secret}' | base64 -d`.
apiVersion: v1
kind: Secret
metadata:
  name: runner-secret
  namespace: drone
type: Opaque
data:
  secret: "<base64>"
