apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: drone
  name: server-data
spec:
  storageClassName: yc-network-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
