# How to view password: `kubectl get secret docker-pull-credentials -n drone -o jsonpath='{.data}' | jq -r .\".dockerconfigjson\" |  base64 -d`.
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: docker-pull-credentials
  namespace: drone
data:
  .dockerconfigjson: |
    "<base64 encoded file>"
