# echo -n 'secret' | base64
# How to view password: `kubectl get secret bot-secret -n boredbot -o jsonpath='{.data.secret}' | base64 -d`.
apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
  namespace: boredbot
type: Opaque
data:
  secret: "<base64>"
