# How to view password: `kubectl get secret service-account-key -n boredbot -o jsonpath='{.data.yc-sa-key}' | base64 -d`.
apiVersion: v1
kind: Secret
metadata:
  name: service-account-key
  namespace: boredbot
type: Opaque
data:
  yc-sa-key: "<base64>"
