apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
  namespace: buildbarn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  serviceName: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      initContainers:
      - name: volume-init
        image: busybox:1.31.1-uclibc
        command:
        - sh
        - -c
        - mkdir -m 0700 -p /storage-cas/persistent_state /storage-ac/persistent_state
        volumeMounts:
        - mountPath: /storage-cas
          name: cas
        - mountPath: /storage-ac
          name: ac
      containers:
      - args:
        - /config/storage.jsonnet
        image: buildbarn/bb-storage:20220912T104841Z-b7137ec
        name: storage
        ports:
        - containerPort: 8981
          protocol: TCP
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
        - mountPath: /storage-cas
          name: cas
        - mountPath: /storage-ac
          name: ac
        resources:
          requests:
            memory: "200M"
            cpu: "50m"
          limits:
            memory: "800M"
            cpu: "100m"
      volumes:
      - name: configs
        projected:
          sources:
          - configMap:
              name: storage
              items:
              - key: storage.jsonnet
                path: storage.jsonnet
          - configMap:
              name: common
              items:
              - key: common.libsonnet
                path: common.libsonnet
  volumeClaimTemplates:
  - metadata:
      name: cas
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
  - metadata:
      name: ac
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  name: storage
  namespace: buildbarn
spec:
  clusterIP: None
  ports:
  - port: 8981
    protocol: TCP
    name: grpc
  selector:
    app: storage
