# How to generate password: `cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 20 | base64`.
# How to view password: `kubectl get secret secret -n keel -o jsonpath='{.data.admin-password}' | base64 -d`.
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: keel
type: Opaque
data:
  admin-password: "<base64>"
