apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: keel
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: yc-network-hdd
  resources:
    requests:
      storage: "10Gi"
